---
wsdir : '~/.config/initmux/wspaces'
sdir  : '~/.config/initmux/sessions'
terminal: 'termite'
#
#skel: #{
#
#  nvim: &nvim
#    - mkdir -p .nvim/vws
#    - touch .nvim/vws/<wname> 
#    - nvim -c ":VWSLoadWorkSpace <wname>"
#
#  ranger1: &ranger1
#    - ranger
#
#  ranger2: &ranger2
#    - ranger
#    - ranger
#
## }    
