---
name: Project
root: /i/project
windows:
- IniTmux : two
- VWS     : two
- Root: 
    panes: 2
models:
    two:
        layout: tiled
        dir: <WindowName>
        panes:
        - vim -c VWSLoadWorkSpace
        - ''
