---
name: Project
root: /i/project
windows:
- IniTmux:
    model: two
    dir  : <WName>/master

- VWS     : two

- Root: 2

models:
    two:
        layout: tiled
        dir: <WindowName>
        panes:
        - vim -c VWSLoadWorkSpace
        - ''
