---
name: Project
root: /i/project
windows:
- VWS     : two
- tmux    : two

- Root: 2

models:
    two:
        layout: tiled
        dir: <WindowName>
        panes:
        - vim -c VWSLoadWorkSpace
        - ''
